### ISSUE TITLE
ValueError: 'sequential/conv2d/BiasAdd__6:0/' is not a valid scope name

### ISSUE THREAD

**Issue by deekshith1352** [catmanifold/onnx2keras#143]
Traceback (most recent call last):
  File "D:/onnx2keras-master/dd.py", line 8, in <module>
    k_model = onnx_to_keras(onnx_model, ['input'])
  File "D:\onnx2keras-master\onnx2keras\converter.py", line 182, in onnx_to_keras
    keras_names
  File "D:\onnx2keras-master\onnx2keras\reshape_layers.py", line 30, in convert_transpose
    layers[node_name] = permute(layers[input_name])
  File "C:\Users\21768\Anaconda3\envs\conv\lib\site-packages\keras\engine\base_layer.py", line 977, in __call__
    input_list)
  File "C:\Users\21768\Anaconda3\envs\conv\lib\site-packages\keras\engine\base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "C:\Users\21768\Anaconda3\envs\conv\lib\site-packages\keras\engine\base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "C:\Users\21768\Anaconda3\envs\conv\lib\site-packages\keras\engine\base_layer.py", line 880, in _infer_output_signature
    with backend.name_scope(self._name_scope()):  # pylint: disable=not-callable
  File "C:\Users\21768\Anaconda3\envs\conv\lib\site-packages\tensorflow\python\framework\ops.py", line 6729, in __enter__
    scope_name = scope.__enter__()
  File "C:\Users\21768\Anaconda3\envs\conv\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\21768\Anaconda3\envs\conv\lib\site-packages\tensorflow\python\framework\ops.py", line 4279, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'sequential/conv2d/BiasAdd__6:0/' is not a valid scope name

**Comment by deekshith1352** [comment]
its a pretrained model. i got it from web how to fix the issue with layer name of pretrained model

**Comment by aspratyush** [comment]
adding: `name_policy='renumerate'` has worked at times for me.
